[package]
name = "poc_tickets_component"
version = "0.1.0"
edition = "2023_01"


[dependencies]
starknet = "2.6.3"


[[target.starknet-contract]]


[lib]



# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
